name: news_clean_architecture
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management
  flutter_bloc: ^9.1.0

  # comparing dart objects
  equatable: ^2.0.7
  # service locator
  get_it: ^8.0.3

  # date format
  intl: ^0.20.2

  # database
  floor: ^1.5.0

  # remote api reques
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  awesome_dio_interceptor: ^1.3.0

  # hooks
  flutter_hooks: ^0.21.2

  # cached image
  cached_network_image: ^3.4.1
  transparent_image: ^2.0.1

  # navigation
  go_router: ^14.8.1

  # Toast messages
  oktoast: ^3.4.0

  # Color Palatte Generator
  palette_generator: ^0.3.3+6

  # List & Grid View
  auto_animated: ^3.2.0
  auto_animated_list: ^2.0.0

  # svg image
  flutter_svg: ^2.0.17

  cuberto_bottom_bar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
     - family: Outfit
       fonts:
         - asset: assets/fonts/outfit/Outfit-Regular.ttf
         - asset: assets/fonts/outfit/Outfit-Medium.ttf
           weight: 500
         - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/outfit/Outfit-Bold.ttf
           weight: 700
         - asset: assets/fonts/outfit/Outfit-Light.ttf
           weight: 300
